apiVersion: v1
kind: Service
metadata:
  name: inventory-service-service
spec:
  selector:
    app: inventory-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
